export const LOGS_ACTIONS = {
  FETCH: "LOG_ACTION_FETCH",
  FETCH_SUCCESS: "LOG_ACTION_FETCH_SUCCESS",
  FETCH_FAILED: "LOG_ACTION_FETCH_FAILED"
};

export const SUMMARY_ACTIONS = {
  FETCH: "SUMMARY_ACTION_FETCH",
  FETCH_SUCCESS: "SUMMARY_ACTION_FETCH_SUCCESS",
  FETCH_FAILED: "SUMMARY_ACTION_FETCH_FAILED"
}

export const API_METHODS = {
  GET: "get",
  POST: "post",
  PUT: "put",
  DELETE: "delete"
};