export const LOGS_ACTIONS = {
  FETCH: "LOG_ACTION_FETCH",
  FETCH_SUCCESS: "LOG_ACTION_FETCH_SUCCESS",
  FETCH_FAILED: "LOG_ACTION_FETCH_FAILED",
  UPDATE_FIELD: "LOG_ACTION_UPDATE_FIELD",
  MODAL_STATE_CHANGED: "LOG_ACTION_MODAL_STATE_CHANGED",
  CLEAR_FIELDS: "LOG_ACTION_CLEAR_FIELDS",
  INIT_UPDATE_FORM: "LOG_ACTION_INIT_UPDATE_FORM"
};

export const SUMMARY_ACTIONS = {
  FETCH: "SUMMARY_ACTION_FETCH",
  FETCH_SUCCESS: "SUMMARY_ACTION_FETCH_SUCCESS",
  FETCH_BALANCE_SUCCESS: "SUMMARY_ACTION_FETCH_BALANCE_SUCCESS",
  FETCH_FAILED: "SUMMARY_ACTION_FETCH_FAILED"
};

export const CATEGORY = {
  FOOD: "FOOD",
  BILLS: "BILLS",
  HEALTH: "HEALTH",
  TRANSPORT: "TRANSPORT",
  CLOTHES: "CLOTHES",
  LEISURE: "LEISURE",
  EDUCATION: "EDUCATION",
  OTHER: "OTHER",

  // Special
  EXPENSE: "EXPENSE", // group of expense
  INCOME: "INCOME",
  SAVINGS: "SAVINGS"
};

export const CATEGORY_SUMMARY = {
  EXPENSE: "expenseSummary",
  INCOME: "incomeSummary",
  SAVINGS: "savingsSummary"
};

export const API_METHODS = {
  GET: "get",
  POST: "post",
  PUT: "put",
  DELETE: "delete"
};